name: examples
description: Examples folder
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.5.3

dependencies:
  path: ^1.8.0
  ssi: ^3.0.2
  selective_disclosure_jwt: ^1.0.0
  dcql:
    path: ../

false_secrets:
  - ./consts.dart
